apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169663747
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169663747
    app.kubernetes.io/part-of: test-app-169663747
  name: go-169663747
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-169663747
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-169663747
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/1v5bvl6p-tenant/test-app-169663747/go-169663747@sha256:bbd9088f747f3939e45648a10486d51659fa1e4a8dcaf40064d54fab99744bde
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
